### ISSUE TITLE
Add an GIF running the app

### ISSUE THREAD

**Issue by Luccasoli** [Luccasoli/cinema-app#2]
Similar to this: https://github.com/Luccasoli/meals_flutter

**Comment by Cybertron-Avneesh** [comment]
@Luccasoli can I do this?

**Comment by Luccasoli** [comment]
@Cybertron-Avneesh sure!

**Comment by Cybertron-Avneesh** [comment]
@Luccasoli I wanted to add AppLogo too.
can you create an issue and assign it to me?

**Comment by Luccasoli** [comment]
@Cybertron-Avneesh I created the issue #5, comment there so I can assign it to you
